const data = {
  data: {
    source1: [
      {
        Flag_Behavior: null,
        Flag_Opinion: 1,
        Original:
          "The European Social Survey (ESS) is an academically driven cross-national survey that has been conducted across Europe since its establishment in 2001. Every two years, face-to-face interviews are conducted with newly selected, cross-sectional samples.",
        Population: "Adults",
        Suggested:
          "The European Social Survey (ESS) is a biennial cross-national survey of European adults, based on in-person interviews. It tracks attitudes, beliefs and behavior related to social, political, and moral issues in more than 30 European nations.",
        Topic: "Social Issues",
        Variables: 70,
        description:
          "The European Social Survey (ESS) is an academically driven cross-national survey that has been conducted across Europe since its establishment in 2001. Every two years, face-to-face interviews are conducted with newly selected, cross-sectional samples.",
        focus_area: {
          id: "Social Issues",
        },
        geo: "Europe",
        geo_detail: "38 European Countries",
        geo_short: "Europe",
        img: "ess.png",
        long_name: "European Social Survey",
        orig_source: "ess-eric",
        periodicity: "Biennial",
        re3data: "https://www.re3data.org/repository/r3d100010233",
        sample_size_cols: 537,
        sample_size_rows: 64814,
        short_name: "ESS",
        text: null,
        time_period: "2002 - 2018",
        twitter: "https://twitter.com/ESS_Survey",
        type: "Survey",
        url_internal: "ontopic.io/data/ess",
        url_orig: "https://www.europeansocialsurvey.org/",
        wikidata_id: "Q1376959",
        wikipedia_id: "https://en.wikipedia.org/wiki/European_Social_Survey",
      },
      {
        Flag_Behavior: null,
        Flag_Opinion: 1,
        Original:
          "Why does America vote as it does on Election Day? The mission of the American National Election Studies (ANES) is to inform explanations of election outcomes by providing data that support rich hypothesis testing, maximize methodological excellence, measure many variables, and promote comparisons across people, contexts, and time. The ANES serves this mission by providing researchers with a view of the political world through the eyes of ordinary citizens.",
        Population: "Voters",
        Suggested:
          'The American National Election Studies (ANES) is a cross-sectional survey of U.S. voters conducted every 2 to 4 years with the election cycle. The survey collects data on electoral behavior, political participation, and public opinion to address the question "why does America vote as it does on election day?".  Providing insight into the political perspectives of ordinary citizens, the data is widely used by researchers, policy makers, students and journalists.',
        Topic: "Politics",
        Variables: 74,
        description:
          "Why does America vote as it does on Election Day? The mission of the American National Election Studies (ANES) is to inform explanations of election outcomes by providing data that support rich hypothesis testing, maximize methodological excellence, measure many variables, and promote comparisons across people, contexts, and time. The ANES serves this mission by providing researchers with a view of the political world through the eyes of ordinary citizens.",
        focus_area: {
          id: "Voting",
        },
        geo: "United States",
        geo_detail: null,
        geo_short: "U.S.",
        img: "anes.png",
        long_name: "American National Election Studies",
        orig_source: "anes",
        periodicity: "Elections",
        re3data: "https://www.re3data.org/repository/r3d100010851",
        sample_size_cols: null,
        sample_size_rows: 800000,
        short_name: "ANES",
        text: null,
        time_period: "1949-2020",
        twitter: "https://twitter.com/electionstudies?lang=en",
        type: "Survey",
        url_internal: "ontopic.io/data/anes",
        url_orig: "https://electionstudies.org/",
        wikidata_id: "Q465857",
        wikipedia_id:
          "https://en.wikipedia.org/wiki/American_National_Election_Studies",
      },
      {
        Flag_Behavior: null,
        Flag_Opinion: 1,
        Original:
          "The General Social Survey (GSS) has tracked the ‘pulse of America’ since 1972. With a cumulative sample size of over 57,000, this annual survey is widely regarded as ‘the single best source of data on societal trends’. It is widely used by academics, government agencies, and the private sector, and is the basis for 'over 20,000 scholarly publications'.",
        Population: "Adults",
        Suggested:
          "The General Social Survey (GSS) is an annual nationally representative survey of American adults.  It has tracked 'the pulse of America' since 1972, measuring opinion, attitudes and behaviors on a broad range of societal issues such as the role of government, morality, and civil liberties.  Regarded as ‘the single best source of data on societal trends’, it is used by academics, government agencies, and the private sector, and is the basis for 'over 20,000 scholarly publications'.",
        Topic: "Social Issues",
        Variables: 192,
        description:
          "The General Social Survey (GSS) has tracked the ‘pulse of America’ since 1972. With a cumulative sample size of over 57,000, this annual survey is widely regarded as ‘the single best source of data on societal trends’. It is widely used by academics, government agencies, and the private sector, and is the basis for 'over 20,000 scholarly publications'.",
        focus_area: {
          id: "Social Issues",
        },
        geo: "United States",
        geo_detail: null,
        geo_short: "U.S.",
        img: "gss.png",
        long_name: "General Social Survey",
        orig_source: "norc",
        periodicity: "Biennial",
        re3data: "https://www.re3data.org/repository/r3d100010819",
        sample_size_cols: 233,
        sample_size_rows: 417336,
        short_name: "GSS",
        text: null,
        time_period: "1972-2020",
        twitter: "https://twitter.com/gss_norc",
        type: "Survey",
        url_internal: "ontopic.io/data/gss",
        url_orig: "https://gss.norc.org/",
        wikidata_id: "Q4118918",
        wikipedia_id: "https://en.wikipedia.org/wiki/General_Social_Survey",
      },
      {
        Flag_Behavior: null,
        Flag_Opinion: null,
        Original:
          "Behavioral Risk Factor Surveillance System (BRFSS) is the nation’s premier system of health-related telephone surveys that collect state data about U.S. residents regarding their health-related risk behaviors, chronic health conditions, and use of preventive services. Established in 1984 with 15 states, BRFSS now collects data in all 50 states as well as the District of Columbia and three U.S. territories. BRFSS completes more than 400,000 adult interviews each year, making it the largest continuously conducted health survey system in the world.By collecting behavioral health risk data at the state and local level, BRFSS has become a powerful tool for targeting and building health promotion activities. As a result, BRFSS users have increasingly demanded more data and asked for more questions on the survey.",
        Population: "Adults",
        Suggested:
          "The Behavioral Risk Factor Surveillance System (BRFSS) is a large-scale survey of U.S. residents, conducting more than 400,000 telephone interviews each year. It collects data on health-related risky behaviors, chronic health conditions, and the use of preventive services.By collecting behavioral health risk data at the state and local level, BRFSS has become a powerful tool for targeting and building health promotion activities.",
        Topic: "Health",
        Variables: 74,
        description:
          "The Behavioral Risk Factor Surveillance System (BRFSS) is the nation’s premier system of health-related telephone surveys that collect state data about U.S. residents regarding their health-related risk behaviors, chronic health conditions, and use of preventive services.",
        focus_area: {
          id: "Health",
        },
        geo: "United States",
        geo_detail: null,
        geo_short: "U.S.",
        img: "brfss.png",
        long_name: "Behavioral Risk Factor Surveillance System",
        orig_source: "cdc",
        periodicity: "Annual",
        re3data: null,
        sample_size_cols: null,
        sample_size_rows: 1200000,
        short_name: "BRFSS",
        text: null,
        time_period: "1984-2021",
        twitter: null,
        type: null,
        url_internal: "ontopic.io/data/brfss",
        url_orig: "https://www.cdc.gov/brfss/index.html",
        wikidata_id: "Q4880710",
        wikipedia_id:
          "https://en.wikipedia.org/wiki/Behavioral_Risk_Factor_Surveillance_System",
      },
    ],
  },
};

export { data };
